# Generated by Django 4.2.6 on 2023-11-29 07:12

from django.db import migrations, models
import django.db.models.deletion
import nikah.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parokia', '0003_parokia_description'),
        ('member', '0004_member_is_active'),
        ('klerus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nikah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nomor Sertifikat Nikah')),
                ('nikah_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Nikah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('istri', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='nikah_istri_related', to='member.member', verbose_name='Istri')),
                ('nikah_klerus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='klerus.klerus', verbose_name='Klerus Yang Menikahkan')),
                ('parokia', models.ForeignKey(blank=True, limit_choices_to=nikah.models.Nikah.limit_choices_parokia, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parokia.parokia', verbose_name='Parokia')),
                ('pendamping_istri', models.ForeignKey(blank=True, limit_choices_to=nikah.models.Nikah.limit_choices_baptis, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pendamping_istri_related', to='member.member', verbose_name='Pendamping Istri')),
                ('pendamping_suami', models.ForeignKey(blank=True, limit_choices_to=nikah.models.Nikah.limit_choices_baptis, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pendamping_suami_related', to='member.member', verbose_name='Pendamping Suami')),
                ('suami', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='nikah_suami_related', to='member.member', verbose_name='Suami')),
            ],
            options={
                'verbose_name': 'Pernikahan',
                'verbose_name_plural': 'Pernikahan',
                'db_table': 'nikah',
            },
        ),
    ]
