# Generated by Django 4.0.5 on 2022-06-06 03:01

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Anggota', 'verbose_name_plural': 'Anggota'},
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='baptis_anniversary',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='baptis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='baptis_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
