# Generated by Django 4.0.5 on 2022-06-06 03:49

from django.db import migrations, models
import django.utils.timezone
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_options_member_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Anggota', 'verbose_name_plural': 'Daftar Anggota'},
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='member',
            name='baptis_anniversary',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Peringatan'),
        ),
        migrations.AlterField(
            model_name='member',
            name='baptis_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Baptis'),
        ),
        migrations.AlterField(
            model_name='member',
            name='baptis_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nama Baptis'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=20, verbose_name='Alamat Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='father',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nama Ayah'),
        ),
        migrations.AlterField(
            model_name='member',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, verbose_name='Koordinat GoogleMap'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_alive',
            field=models.BooleanField(default=True, verbose_name='Hidup/Almarhum'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mother',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nama Ibu'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telpon/HP'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pob',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tempat Lahir'),
        ),
    ]
