# Generated by Django 4.2.6 on 2023-11-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_pekerjaan_member_pendidikan'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Masih Bersama'),
        ),
    ]
