# Generated by Django 4.0.5 on 2022-06-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_options_member_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.FileField(blank=True, upload_to='', verbose_name='Photo'),
        ),
    ]
