# Generated by Django 4.0.5 on 2022-06-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='baptis_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nomor Sertifikat Baptis'),
        ),
    ]
