# Generated by Django 4.0.5 on 2022-06-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_member_baptis_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_alive',
            field=models.BooleanField(default=True, verbose_name='Masih Hidup'),
        ),
    ]
