# Generated by Django 4.0.5 on 2022-06-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_member_is_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nama Lengkap'),
        ),
    ]
