# Generated by Django 4.0.5 on 2022-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_alter_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_klerus',
            field=models.BooleanField(default=False, verbose_name='Klerus'),
        ),
    ]
