# Generated by Django 4.0.5 on 2022-06-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_member_is_klerus'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, verbose_name='Catatan'),
        ),
    ]
