# Generated by Django 4.0.5 on 2022-06-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_member_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='jabatan_klerus',
            field=models.CharField(blank=True, max_length=20, verbose_name='Jabatan Klerus'),
        ),
    ]
