# Generated by Django 4.2.6 on 2023-11-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Etnik',
                'db_table': 'etnik',
            },
        ),
    ]
