# Generated by Django 4.2.6 on 2023-11-02 10:06

import baptis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klerus', '0001_initial'),
        ('parokia', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baptis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nomor Sertifikat Baptis')),
                ('baptis_name', models.CharField(max_length=50, verbose_name='Nama Baptis')),
                ('baptis_anniversary', models.DateField(blank=True, null=True, verbose_name='Tanggal Peringatan')),
                ('baptis_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Baptis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baptis_klerus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='klerus.klerus', verbose_name='Klerus Yang Membaptis')),
                ('baptis_parent', models.ForeignKey(blank=True, limit_choices_to=baptis.models.Baptis.limit_choices_baptis, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='baptis_parent_related', to='member.member', verbose_name='Orang Tua Baptis')),
                ('komox', models.ForeignKey(blank=True, limit_choices_to=baptis.models.Baptis.limit_choices_komox, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parokia.komox', verbose_name='Komox')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='baptis_member_related', to='member.member', verbose_name='Yang Di Baptis')),
                ('parokia', models.ForeignKey(blank=True, limit_choices_to=baptis.models.Baptis.limit_choices_parokia, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parokia.parokia', verbose_name='Parokia')),
            ],
            options={
                'verbose_name': 'Baptis',
                'verbose_name_plural': 'Daftar Baptis',
                'db_table': 'baptis',
            },
        ),
    ]
