# Generated by Django 4.0.5 on 2022-06-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klerus', '0001_initial'),
        ('member', '0001_initial'),
        ('parokia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baptis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('baptis_klerus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='klerus.klerus')),
                ('baptis_parent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='baptis_parent_related', to='member.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='baptis_member_related', to='member.member')),
                ('parokia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parokia.parokia')),
            ],
            options={
                'verbose_name': 'Baptis',
                'db_table': 'baptis',
            },
        ),
    ]
