# Generated by Django 4.0.5 on 2022-06-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baptis',
            options={'verbose_name': 'Baptis', 'verbose_name_plural': 'Daftar Baptis'},
        ),
        migrations.AddField(
            model_name='baptis',
            name='baptis_anniversary',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baptis',
            name='baptis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baptis',
            name='baptis_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
