# Generated by Django 4.0.5 on 2022-06-06 03:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('klerus', '0003_klerus_created_at_klerus_updated_at_and_more'),
        ('parokia', '0003_alter_parokia_address_alter_parokia_code_and_more'),
        ('member', '0004_alter_member_options_member_created_at_and_more'),
        ('baptis', '0002_alter_baptis_options_baptis_baptis_anniversary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baptis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='baptis',
            name='baptis_anniversary',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Peringatan'),
        ),
        migrations.AlterField(
            model_name='baptis',
            name='baptis_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Baptis'),
        ),
        migrations.AlterField(
            model_name='baptis',
            name='baptis_klerus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='klerus.klerus', verbose_name='Klerus Yang Membaptis'),
        ),
        migrations.AlterField(
            model_name='baptis',
            name='baptis_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nama Baptis'),
        ),
        migrations.AlterField(
            model_name='baptis',
            name='baptis_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='baptis_parent_related', to='member.member', verbose_name='Orang Tua Baptis'),
        ),
        migrations.AlterField(
            model_name='baptis',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='baptis_member_related', to='member.member', verbose_name='Yang Di Baptis'),
        ),
        migrations.AlterField(
            model_name='baptis',
            name='number',
            field=models.CharField(max_length=30, verbose_name='Nomor Sertifikat Baptis'),
        ),
        migrations.AlterField(
            model_name='baptis',
            name='parokia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parokia.parokia', verbose_name='Nama Parokia'),
        ),
    ]
