# Generated by Django 4.0.5 on 2022-06-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptis', '0003_baptis_created_at_baptis_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptis',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nomor Sertifikat Baptis'),
        ),
    ]
