# Generated by Django 4.0.5 on 2022-06-06 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klerus', '0005_remove_klerus_baptis_name_alter_klerus_name'),
        ('member', '0010_alter_member_name'),
        ('baptis', '0005_alter_baptis_baptis_klerus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptis',
            name='baptis_klerus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='klerus.klerus', verbose_name='Klerus Yang Membaptis'),
        ),
        migrations.AlterField(
            model_name='baptis',
            name='baptis_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='baptis_parent_related', to='member.member', verbose_name='Orang Tua Baptis'),
        ),
        migrations.AlterField(
            model_name='baptis',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='baptis_member_related', to='member.member', verbose_name='Yang Di Baptis'),
        ),
    ]
