# Generated by Django 4.0.5 on 2022-06-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parokia', '0004_parokia_email'),
        ('baptis', '0006_alter_baptis_baptis_klerus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptis',
            name='parokia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parokia.parokia', verbose_name='Nama Parokia'),
        ),
    ]
