# Generated by Django 4.2.6 on 2023-11-02 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JabatanKlerus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Jabatan')),
            ],
            options={
                'verbose_name': 'Jabatan Klerus',
                'verbose_name_plural': 'Jabatan Klerus',
                'db_table': 'jabatan_klerus',
            },
        ),
        migrations.CreateModel(
            name='Klerus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='klerus.jabatanklerus', verbose_name='Jabatan')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='member.member', verbose_name='Name Klerus')),
            ],
            options={
                'verbose_name': 'Klerus',
                'verbose_name_plural': 'Daftar Klerus',
                'db_table': 'klerus',
            },
        ),
    ]
