# Generated by Django 4.2.6 on 2023-11-02 08:08

from django.db import migrations, models
import django.db.models.deletion
import klerus.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('klerus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klerus',
            name='jabatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='klerus.jabatanklerus', verbose_name='Jabatan Klerus'),
        ),
        migrations.AlterField(
            model_name='klerus',
            name='member',
            field=models.OneToOneField(limit_choices_to=klerus.models.Klerus.limit_member_baptis, on_delete=django.db.models.deletion.RESTRICT, to='member.member', verbose_name='Name Klerus'),
        ),
    ]
