# Generated by Django 4.0.5 on 2022-06-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klerus', '0003_klerus_created_at_klerus_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klerus',
            name='baptis_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nama Baptis'),
        ),
        migrations.AddField(
            model_name='klerus',
            name='jabatan',
            field=models.CharField(choices=[('ROMO', 'ROMO'), ('ROMODIAKON', 'ROMO DIAKON'), ('SUBDIAKEN', 'SUB-DIAKEN')], default='ROMO', max_length=20, verbose_name='Jabatan Klerus'),
        ),
        migrations.AlterField(
            model_name='klerus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama Lengkap'),
        ),
    ]
