# Generated by Django 4.0.5 on 2022-06-06 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_alter_member_name'),
        ('klerus', '0004_klerus_baptis_name_klerus_jabatan_alter_klerus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klerus',
            name='baptis_name',
        ),
        migrations.AlterField(
            model_name='klerus',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='member.member', verbose_name='Name Klerus'),
        ),
    ]
