# Generated by Django 4.0.5 on 2022-06-04 17:55

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klerus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parokia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('klerus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='klerus.klerus')),
            ],
            options={
                'verbose_name': 'Parokia',
                'db_table': 'parokia',
            },
        ),
    ]
