# Generated by Django 4.2.6 on 2023-11-01 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('klerus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parokia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Parokia')),
                ('code', models.CharField(help_text='Kode Parokia bisa menggunakan singkatan. Contoh: JSPP untuk Js Petrus dan Paulus', max_length=10, unique=True, verbose_name='Kode Parokia')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Alamat')),
                ('geolocation', models.CharField(blank=True, max_length=250, verbose_name='Koordinat GoogleMap')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Alamat Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telpon/HP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('klerus_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parokia_klerus_1', to='klerus.klerus', verbose_name='Nama Klerus 1')),
                ('klerus_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parokia_klerus_2', to='klerus.klerus', verbose_name='Nama Klerus 2')),
            ],
            options={
                'verbose_name': 'Parokia',
                'verbose_name_plural': 'Daftar Parokia',
                'db_table': 'parokia',
            },
        ),
        migrations.CreateModel(
            name='Komox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Komox')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode Komox')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Alamat')),
                ('geolocation', models.CharField(blank=True, max_length=250, verbose_name='Koordinat GoogleMap')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Alamat Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telpon/HP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('koordinator_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='koordinator_1', to='member.member', verbose_name='Koordinator 1')),
                ('koordinator_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='koordinator_2', to='member.member', verbose_name='Koordinator 2')),
            ],
            options={
                'verbose_name': 'Komunitas Orthodox',
                'verbose_name_plural': 'Daftar Komox',
                'db_table': 'komox',
            },
        ),
    ]
