# Generated by Django 4.2.6 on 2023-11-04 23:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parokia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komox',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='parokia',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
