# Generated by Django 4.0.5 on 2022-06-06 03:49

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('klerus', '0003_klerus_created_at_klerus_updated_at_and_more'),
        ('parokia', '0002_alter_parokia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parokia',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='parokia',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kode Parokia'),
        ),
        migrations.AlterField(
            model_name='parokia',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, verbose_name='Koordinat GoogleMap'),
        ),
        migrations.AlterField(
            model_name='parokia',
            name='klerus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='klerus.klerus', verbose_name='Nama Klerus'),
        ),
        migrations.AlterField(
            model_name='parokia',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama Parokia'),
        ),
        migrations.AlterField(
            model_name='parokia',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telpon/HP'),
        ),
    ]
