# Generated by Django 4.0.5 on 2022-06-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parokia', '0003_alter_parokia_address_alter_parokia_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parokia',
            name='email',
            field=models.EmailField(blank=True, max_length=20, verbose_name='Alamat Email'),
        ),
    ]
