# Generated by Django 4.0.5 on 2022-06-06 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klerus', '0005_remove_klerus_baptis_name_alter_klerus_name'),
        ('parokia', '0004_parokia_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parokia',
            name='klerus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='klerus.klerus', verbose_name='Nama Klerus'),
        ),
    ]
