# Generated by Django 4.0.5 on 2022-06-07 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klerus', '0005_remove_klerus_baptis_name_alter_klerus_name'),
        ('parokia', '0006_alter_parokia_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parokia',
            name='klerus',
        ),
        migrations.AddField(
            model_name='parokia',
            name='klerus_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parokia_klerus_1', to='klerus.klerus', verbose_name='Nama Klerus 1'),
        ),
        migrations.AddField(
            model_name='parokia',
            name='klerus_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parokia_klerus_2', to='klerus.klerus', verbose_name='Nama Klerus 2'),
        ),
    ]
