# Generated by Django 4.0.5 on 2022-06-07 03:13

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_member_jabatan_klerus'),
        ('parokia', '0007_remove_parokia_klerus_parokia_klerus_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Komox')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode Komox')),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, verbose_name='Alamat')),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, verbose_name='Koordinat GoogleMap')),
                ('email', models.EmailField(blank=True, max_length=20, verbose_name='Alamat Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telpon/HP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('koordinator_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='koordinator_1', to='member.member', verbose_name='Koordinator 1')),
                ('koordinator_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='koordinator_2', to='member.member', verbose_name='Koordinator 2')),
            ],
            options={
                'verbose_name': 'Komunitas Orthodox',
                'verbose_name_plural': 'Daftar Komox',
                'db_table': 'komox',
            },
        ),
    ]
