# Generated by Django 4.0.5 on 2022-06-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parokia', '0008_komox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komox',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Alamat Email'),
        ),
        migrations.AlterField(
            model_name='parokia',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Alamat Email'),
        ),
    ]
